### ISSUE TITLE
Getting traction on reddit!

### ISSUE THREAD

**Issue by dylanking42** [josephsdavid/N2D#13]
https://www.reddit.com/r/MachineLearning/comments/g1dgge/d_how_do_you_cluster_data_with_mixed_data_both/fnjdi9l?utm_source=share&utm_medium=web2x

You're famous now! 🥇 😉

**Comment by josephsdavid** [comment]
Thanks for sharing :D ! I’ll be turning in my thesis on Monday so expect lots of updates soon!!!
