### ISSUE TITLE
can I use the library with GPU?

### ISSUE THREAD

**Issue by dvaler01** [josephsdavid/N2D#6]
Hello David,

I installed the n2d library and I run my first demo but it seems to working on CPU. Can I use GPU or the library for now is implemented only for CPU?

Dimitris.

**Comment by josephsdavid** [comment]
Yes sir! If you have tensorflow with CUDA support installed, it should run on GPU (it does on my computer). You can test if you’re able to use GPU using one of these functions: https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available

Hopefully this gets you fixed up!

**Comment by josephsdavid** [comment]
I’ll update the installation instructions I think

**Comment by dvaler01** [comment]
Hello David,

Everything is fine. The library is working perfectly. Now I am looking the implementation because I am going to customize some functions.

Thank you for your help. :)

**Comment by josephsdavid** [comment]
Great! Glad everything is together :) let me know if anything can be changed/improved for easier use!
