### ISSUE TITLE
random seeds for auto encoder

### ISSUE THREAD

**Issue by stellaywu** [josephsdavid/N2D#9]
Hey @josephsdavid! Another question -  Is there a random seeds setting for the auto-encoder? Trying to have reproducible results Thanks! 

Also would it be possible to add automatic choice of number of clusters for non dbscan based clustering methods? 

Stella

**Comment by josephsdavid** [comment]
https://www.tensorflow.org/api_docs/python/tf/random/set_seed for now, you can do it through tensorflow! Will add a more convenient way to do it  to the next update! Yeah let me think how automatic clustering would work, longer term project for that :)

**Comment by josephsdavid** [comment]
Once trained, the autoencoders **should** be deterministic, but since they are optimized through SGD without setting a seed results of training might be slightly different. Ideally we would want to initialize the N2D object with a seed that is constant throughout all steps of the process

**Comment by stellaywu** [comment]
thanks!
